src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CompteRepository::class)]
class Compte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: "string", length: 255)]
    private ?string $num_compte = null;
    

    #[ORM\Column(length: 255)]
    private ?string $Type_compte = null;

 

    #[ORM\OneToMany(mappedBy: 'compte', targetEntity: CarteBancaire::class)]
    private Collection $relation;


    #[ORM\OneToMany(mappedBy: 'compte', targetEntity: Etablissement::class)]
    private Collection $etablissements;



    public function getEtablissements(): Collection
    {
        return $this->etablissements;
    }

    // Add method to add an Etablissement
    public function addEtablissement(Etablissement $etablissement): self
    {
        if (!$this->etablissements->contains($etablissement)) {
            $this->etablissements[] = $etablissement;
            $etablissement->setCompte($this);
        }

        return $this;
    }

    // Add method to remove an Etablissement
    public function removeEtablissement(Etablissement $etablissement): self
    {
        if ($this->etablissements->removeElement($etablissement)) {
            // set the owning side to null (unless already changed)
            if ($etablissement->getCompte() === $this) {
                $etablissement->setCompte(null);
            }
        }

        return $this;
    }

    public function __construct()
    {
                $this->num_compte = 'AL' . $this->generateRandomNumber(10);
                $this->etablissements = new ArrayCollection();
        $this->relation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCompte(): ?string
    {
        return $this->num_compte;
    }

    public function setNumCompte(string $num_compte): self {
        $this->num_compte = $num_compte;
        return $this;
    }

    


    public function getTypeCompte(): ?string
    {
        return $this->Type_compte;
    }

    public function setTypeCompte(string $Type_compte): static
    {
        $this->Type_compte = $Type_compte;

        return $this;
    }

  

    /**
     * @return Collection<int, CarteBancaire>
     */
    public function getRelation(): Collection
    {
        return $this->relation;
    }

    public function addRelation(CarteBancaire $relation): static
    {
        if (!$this->relation->contains($relation)) {
            $this->relation->add($relation);
            $relation->setCompte($this);
        }

        return $this;
    }

    public function removeRelation(CarteBancaire $relation): static
    {
        if ($this->relation->removeElement($relation)) {
            // set the owning side to null (unless already changed)
            if ($relation->getCompte() === $this) {
                $relation->setCompte(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->id;
    }


    private function generateRandomNumber($length) {
        $numbers = '0123456789';
        $numberStr = '';
        for ($i = 0; $i < $length; $i++) {
            $numberStr .= $numbers[rand(0, strlen($numbers) - 1)];
        }
        return $numberStr;
    }


}

src/Form/CompteType.php
<?php

namespace App\Form;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use App\Entity\Compte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Entity\Etablissement; // Import the Etablissement class


class CompteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_compte', TextType::class, [
                'disabled' => true,
                'attr' => ['readonly' => true]
            ])
            ->add('Type_compte', ChoiceType::class, [
                'choices' => [
                    'Epargne' => 'Epargne',
                    'Courant' => 'Courant',
                ],
                'label' => 'Type de compte',
                // Add any other options you might need
            ]);
            
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Compte::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Compte;
use App\Form\CompteType;
use App\Repository\CompteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/compte')]
class CompteController extends AbstractController
{
    #[Route('/', name: 'app_compte_index', methods: ['GET'])]
    public function index(CompteRepository $compteRepository): Response
    {
        return $this->render('compte/index.html.twig', [
            'comptes' => $compteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_compte_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $compte = new Compte();
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($compte);
            $entityManager->flush();

            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('compte/new.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_compte_show', methods: ['GET'])]
    public function show(Compte $compte): Response
    {
        return $this->render('compte/show.html.twig', [
            'compte' => $compte,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_compte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Compte $compte, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('compte/edit.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_compte_delete', methods: ['POST'])]
    public function delete(Request $request, Compte $compte, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$compte->getId(), $request->request->get('_token'))) {
            $entityManager->remove($compte);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
    }





    public function createCompte(Request $request): Response
{
    $compte = new Compte();
    $form = $this->createForm(CompteType::class, $compte);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
        // Save the compte data, etc.
    } else {
        // Handle form errors, show them back in the template
    }

    return $this->render('compte/new.html.twig', [
        'form' => $form->createView(),
    ]);
}

}

templates/compte/_delete_form.html.twig
<form method="post" action="{{ path('app_compte_delete', {'id': compte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ compte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/compte/_form.html.twig
{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}

{% for field in form %}
  <div class="mb-3">
    {{ form_row(field, {
      'label_attr': {'class': 'form-label'},
      'attr': {'class': 'form-control'},
      'error_bubbling': true
    }) }}
    {# Check if there are errors and display the first one #}
    {% if field.vars.errors|length > 0 %}
      <div class="invalid-feedback d-block">
        {{ field.vars.errors|first.message }}
      </div>
    {% endif %}
  </div>
{% endfor %}

<button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/compte/edit.html.twig
{% extends 'basefront.html.twig' %}


{% block title %}Edit Compte{% endblock %}

{% block body %}
    <h1>Edit Compte</h1>

    {{ include('compte/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-dark" href="{{ path('app_compte_index') }}">back to list</a>

    {{ include('compte/_delete_form.html.twig') }}
{% endblock %}

templates/compte/index.html.twig
{% extends 'basefront.html.twig' %}


{% block title %}Compte index{% endblock %}

{% block body %}
    <h1>Compte index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_compte</th>
                <th>Type_compte</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for compte in comptes %}
            <tr>
                <td>{{ compte.id }}</td>
                <td>{{ compte.numCompte }}</td>
                <td>{{ compte.TypeCompte }}</td>
                <td>
                    <a href="{{ path('app_compte_show', {'id': compte.id}) }}">show</a>
                    <a href="{{ path('app_compte_edit', {'id': compte.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_compte_new') }}">Create new</a>
{% endblock %}

templates/compte/new.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}New Compte{% endblock %}

{% block body %}

<div class="container mt-5">
    <h1>Create new Compte</h1>

    {{ include('compte/_form.html.twig') }}

    <a class="btn btn-dark" href="{{ path('app_compte_index') }}">back to list</a>
</div>
{% endblock %}

templates/compte/show.html.twig
{% extends 'basefront.html.twig' %}


{% block title %}Compte{% endblock %}

{% block body %}
    <h1>Compte</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ compte.id }}</td>
            </tr>
            <tr>
                <th>Num_compte</th>
                <td>{{ compte.numCompte }}</td>
            </tr>

            <tr>
                <th>Type_compte</th>
                <td>{{ compte.TypeCompte }}</td>
            </tr>
           
        </tbody>
    </table>

    <a class="btn btn-secondary" href="{{ path('app_compte_index') }}">back to list</a>

    <a class="btn btn-primary" href="{{ path('app_compte_edit', {'id': compte.id}) }}">edit</a>

    {{ include('compte/_delete_form.html.twig') }}
{% endblock %}